name: Construire l'image Docker

on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v2
      - name: Connexion à Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire et pousser l'image Docker
        run: |
          docker buildx build --platform linux/amd64 -t emmanuelntankeu/4dvp:latest ./super_calculator
          docker push emmanuelntankeu/4dvp:latest
