name: Dependabot
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependabot pour Go
        uses: dependabot/dependabot-core@v0.164.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          update: "all"
          package-ecosystem: "gomod"
          registry-url: "https://proxy.golang.org"
      - name: Dependabot pour Docker
        uses: dependabot/dependabot-core@v0.164.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          update: "all"
          package-ecosystem: "docker"
          registry-url: "https://proxy.golang.org"
