name: Code Analysis

on:
  pull_request:
  push:
  workflow_dispatch:  # Déclencheur pour l'exécution manuelle

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: |
          sudo apt-get update
          sudo apt-get install -y semgrep

      - name: Static Analysis with Semgrep
        run: semgrep .

  docker-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Analysis with Hadolint
        run: hadolint Dockerfile

  super-linter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: github/super-linter@v4
        with:
          flags: "--json"
