name: code Analystate

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      - name: Analyse Dockerfile avec hadolint
        run: |
          docker run --rm -i hadolint/hadolint < ./super_calculator/Dockerfile
      - name: Analyse statitsique avec semgrep          
        run: |
            wget -O semgrep https://github.com/returntocorp/semgrep/releases/latest/download/semgrep-linux
            chmod +x semgrep
            ./semgrep --config=p/r2c-ci ./super_calculator/Dockerfile
