name: code Analystate

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      - name: Analyse Dockerfile avec hadolint
        run: |
          docker pull hadolint/hadolint:v1.22.1
          docker run --rm -i hadolint/hadolint:v1.22.1 < ./super_calculator/Dockerfile
